# This workflow will do a clean installation of node dependencies, cache/restore them, run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TestLinting


on:
  push:
    branches: '**'
  pull_request:
    branches: '**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Scheduled test'
        type: boolean


# defaults:
#   run:
#     working-directory: veritable-react-gui
